version: "3.9"

services:
  frontend:
    image: elonaire/billboards-frontend:latest
    expose:
      - "80"
    networks:
      - app-network

  backend:
    build: .
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
