version: "3.9"

services:
  frontend:
    image: elonaire/billboards-frontend:latest
    expose:
      - "80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: elonaire/billboards-backend:latest
    environment:
      - NODE_ENV=development
    restart: always
    depends_on:
      - mongodb
    expose:
      - "3000"
    networks:
      - app-network

  mongodb:
    image: mongo:4.4-bionic
    container_name: mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - mongodb
    networks:
      - app-network

volumes:
  mongodb:
  - mongodb-data
networks:
  app-network:
    driver: bridge
